/* Ataraxia — background image pool (data only)
 * Exports: BACKGROUNDS (global array)
 * Régénéré par le labo photo local (scripts/photo-lab-lib.js).
 */
const BACKGROUNDS = [
  {
    url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=90&auto=format&fit=max",
    credit: "Samuel Ferrara",
    link: "https://unsplash.com/@samferrara",
    source: "Unsplash",
    title: "Alpine Summit",
  },
  {
    url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1920&q=90&auto=format&fit=max",
    credit: "Luca Bravo",
    link: "https://unsplash.com/@lucabravo",
    source: "Unsplash",
    title: "Forest Light",
  },
  {
    url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1920&q=90&auto=format&fit=max",
    credit: "Benjamin Voros",
    link: "https://unsplash.com/@vorosbenisop",
    source: "Unsplash",
    title: "Starry Mountains",
  },
  {
    url: "https://images.unsplash.com/photo-1505144808419-1957a94ca61e?w=1920&q=90&auto=format&fit=max",
    credit: "Frank McKenna",
    link: "https://unsplash.com/@frankiefoto",
    source: "Unsplash",
    title: "Northern Lights",
  },
  {
    url: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1920&q=90&auto=format&fit=max",
    credit: "David Marcu",
    link: "https://unsplash.com/@davidmarcu",
    source: "Unsplash",
    title: "Sun Through Trees",
  },
  {
    url: "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=1920&q=90&auto=format&fit=max",
    credit: "Robert Lukeman",
    link: "https://unsplash.com/@robertlukeman",
    source: "Unsplash",
    title: "Lake Reflection",
  },
  {
    url: "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=1920&q=90&auto=format&fit=max",
    credit: "Kazuend",
    link: "https://unsplash.com/@kazuend",
    source: "Unsplash",
    title: "Waterfall Forest",
  },
  {
    url: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1920&q=90&auto=format&fit=max",
    credit: "Pietro De Grandi",
    link: "https://unsplash.com/@pietrozj",
    source: "Unsplash",
    title: "Mountain Sunrise",
  },
  {
    url: "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=1920&q=90&auto=format&fit=max",
    credit: "Luca Bravo",
    link: "https://unsplash.com/@lucabravo",
    source: "Unsplash",
    title: "Night Sky",
  },
  {
    url: "https://images.unsplash.com/photo-1426604966848-d7adac402bff?w=1920&q=90&auto=format&fit=max",
    credit: "Ian Dooley",
    link: "https://unsplash.com/@sadswim",
    source: "Unsplash",
    title: "Desert Sands",
  },
  {
    url: "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=1920&q=90&auto=format&fit=max",
    credit: "Luca Upper",
    link: "https://unsplash.com/@lucaupper",
    source: "Unsplash",
    title: "Golden Road",
  },
  {
    url: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=1920&q=90&auto=format&fit=max",
    credit: "Joanna Kosinska",
    link: "https://unsplash.com/@joannakosinska",
    source: "Unsplash",
    title: "Lavender Fields",
  },
  {
    url: "https://images.unsplash.com/photo-1518173946687-a4c8892bbd9f?w=1920&q=90&auto=format&fit=max",
    credit: "Ricardo Gomez Angel",
    link: "https://unsplash.com/@rgaleriacom",
    source: "Unsplash",
    title: "Spiral Galaxy",
  },
  {
    url: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=1920&q=90&auto=format&fit=max",
    credit: "Luca Zanon",
    link: "https://unsplash.com/@luca_zanon",
    source: "Unsplash",
    title: "Snowy Trees",
  },
  {
    url: "https://images.unsplash.com/photo-1542401886-65d6c61db217?w=1920&q=90&auto=format&fit=max",
    credit: "v2osk",
    link: "https://unsplash.com/@v2osk",
    source: "Unsplash",
    title: "Volcanic Landscape",
  },
  {
    url: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1920&q=90&auto=format&fit=max",
    credit: "Kalen Emsley",
    link: "https://unsplash.com/@kalenemsley",
    source: "Unsplash",
    title: "Mountain Peak",
  },
  {
    url: "https://images.unsplash.com/photo-1536431311719-398b6704d4cc?w=1920&q=90&auto=format&fit=max",
    credit: "Vincentiu Solomon",
    link: "https://unsplash.com/@vincentiu",
    source: "Unsplash",
    title: "Milky Way",
  },
  {
    url: "https://images.unsplash.com/photo-1491002052546-bf38f186af56?w=1920&q=90&auto=format&fit=max",
    credit: "Austin Neill",
    link: "https://unsplash.com/@arstyy",
    source: "Unsplash",
    title: "Autumn Forest",
  },
  {
    url: "https://images.unsplash.com/photo-1444080748397-f442aa95c3e5?w=1920&q=90&auto=format&fit=max",
    credit: "Josh Gordon",
    link: "https://unsplash.com/@joshgordon",
    source: "Unsplash",
    title: "Desert Stars",
  },
  {
    url: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1920&q=90&auto=format&fit=max",
    credit: "Jonatan Pie",
    link: "https://unsplash.com/@r3dmax",
    source: "Unsplash",
    title: "Aurora Borealis",
  },
  {
    url: "https://images.unsplash.com/photo-1520942702018-0862200e6873?w=1920&q=90&auto=format&fit=max",
    credit: "Silas Baisch",
    link: "https://unsplash.com/@silasbaisch",
    source: "Unsplash",
    title: "Ocean Shore",
  },
  {
    url: "https://images.unsplash.com/photo-1414609245224-afa02bfb3fda?w=1920&q=90&auto=format&fit=max",
    credit: "Jordan McQueen",
    link: "https://unsplash.com/@jordanmcqueen",
    source: "Unsplash",
    title: "Sunrise Coast",
  },
  {
    url: "https://images.unsplash.com/photo-1495616811223-4d98c6e9c869?w=1920&q=90&auto=format&fit=max",
    credit: "Levi Bare",
    link: "https://unsplash.com/@levibare",
    source: "Unsplash",
    title: "Golden Cliffs",
  },
  {
    url: "https://images.pexels.com/photos/1496373/pexels-photo-1496373.jpeg?auto=compress&cs=tinysrgb&w=1920",
    credit: "Trace Hudson",
    link: "https://www.pexels.com/photo/1496373/",
    source: "Pexels",
    title: "Ocean Waves",
  },
  {
    url: "https://images.pexels.com/photos/2166553/pexels-photo-2166553.jpeg?auto=compress&cs=tinysrgb&w=1920",
    credit: "Felix Mittermeier",
    link: "https://www.pexels.com/photo/2166553/",
    source: "Pexels",
    title: "Winter Forest",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/49/%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg/1920px-%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg",
    credit: "The School of Athens — Raphael, 1511",
    link: "https://commons.wikimedia.org/wiki/File:%22The_School_of_Athens%22_by_Raffaello_Sanzio_da_Urbino.jpg",
    source: "Wikimedia Commons · Public Domain",
    culture: "greco-roman",
    focalY: 0.417,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/David_-_The_Death_of_Socrates.jpg/1920px-David_-_The_Death_of_Socrates.jpg",
    credit: "The Death of Socrates — Jacques-Louis David, 1787",
    link: "https://commons.wikimedia.org/wiki/File:David_-_The_Death_of_Socrates.jpg",
    source: "Wikimedia Commons · Public Domain",
    culture: "greco-roman",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Thomas_Cole_-_The_Oxbow_%28The_Connecticut_River_near_Northampton%29.jpg/1920px-Thomas_Cole_-_The_Oxbow_%28The_Connecticut_River_near_Northampton%29.jpg",
    credit: "The Oxbow — Thomas Cole, 1836",
    link: "https://commons.wikimedia.org/wiki/File:Thomas_Cole_-_The_Oxbow_(The_Connecticut_River_near_Northampton).jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg/1920px-Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    credit: "The Starry Night — Vincent van Gogh, 1889",
    link: "https://commons.wikimedia.org/wiki/File:Van_Gogh_-_Starry_Night_-_Google_Art_Project.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/VanGogh-starry_night_ballance1.jpg/1920px-VanGogh-starry_night_ballance1.jpg",
    credit: "Starry Night Over the Rhône — Vincent van Gogh, 1888",
    link: "https://commons.wikimedia.org/wiki/File:VanGogh-starry_night_ballance1.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Caspar_David_Friedrich_-_Der_Mönch_am_Meer_-_Google_Art_Project.jpg/1920px-Caspar_David_Friedrich_-_Der_Mönch_am_Meer_-_Google_Art_Project.jpg",
    credit: "The Monk by the Sea — Caspar David Friedrich, 1810",
    link: "https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Der_M%C3%B6nch_am_Meer_-_Google_Art_Project.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Claude_Monet_-_Water_Lilies_-_1906%2C_Chicago.jpg/1920px-Claude_Monet_-_Water_Lilies_-_1906%2C_Chicago.jpg",
    credit: "Water Lilies — Claude Monet, 1906",
    link: "https://commons.wikimedia.org/wiki/File:Claude_Monet_-_Water_Lilies_-_1906,_Chicago.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/30/The_Fighting_Temeraire%2C_JMW_Turner%2C_National_Gallery.jpg/1920px-The_Fighting_Temeraire%2C_JMW_Turner%2C_National_Gallery.jpg",
    credit: "The Fighting Temeraire — J.M.W. Turner, 1839",
    link: "https://commons.wikimedia.org/wiki/File:The_Fighting_Temeraire,_JMW_Turner,_National_Gallery.jpg",
    source: "Wikimedia Commons · Public Domain",
    focalY: 0.762,
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg/1920px-Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    credit: "The Birth of Venus — Sandro Botticelli, c. 1485",
    link: "https://commons.wikimedia.org/wiki/File:Sandro_Botticelli_-_La_nascita_di_Venere_-_Google_Art_Project_-_edited.jpg",
    source: "Wikimedia Commons · Public Domain",
    culture: "greco-roman",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/The_Hay_Wain_1821.jpg/1920px-The_Hay_Wain_1821.jpg",
    credit: "The Hay Wain — John Constable, 1821",
    link: "https://commons.wikimedia.org/wiki/File:The_Hay_Wain_1821.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Cole_Thomas_The_Oxbow_%28The_Connecticut_River_near_Northampton_1836%29.jpg/1920px-Cole_Thomas_The_Oxbow_%28The_Connecticut_River_near_Northampton_1836%29.jpg",
    credit: "The Oxbow — Thomas Cole, 1836",
    link: "https://commons.wikimedia.org/wiki/File:Cole_Thomas_The_Oxbow_(The_Connecticut_River_near_Northampton_1836).jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Albert_Bierstadt_-_Among_the_Sierra_Nevada%2C_California_-_Google_Art_Project.jpg/1920px-Albert_Bierstadt_-_Among_the_Sierra_Nevada%2C_California_-_Google_Art_Project.jpg",
    credit: "Among the Sierra Nevada, California — Albert Bierstadt, 1868",
    link: "https://commons.wikimedia.org/wiki/File:Albert_Bierstadt_-_Among_the_Sierra_Nevada,_California_-_Google_Art_Project.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Aivazovsky%2C_Ivan_-_The_Ninth_Wave.jpg/1920px-Aivazovsky%2C_Ivan_-_The_Ninth_Wave.jpg",
    credit: "The Ninth Wave — Ivan Aivazovsky, 1850",
    link: "https://commons.wikimedia.org/wiki/File:Aivazovsky,_Ivan_-_The_Ninth_Wave.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Whistler-Nocturne_in_black_and_gold.jpg/1920px-Whistler-Nocturne_in_black_and_gold.jpg",
    credit: "Nocturne in Black and Gold: The Falling Rocket — James McNeill Whistler, 1875",
    link: "https://commons.wikimedia.org/wiki/File:Whistler-Nocturne_in_black_and_gold.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Frederic_Edwin_Church_-_Heart_of_the_Andes_-_Google_Art_Project.jpg/1920px-Frederic_Edwin_Church_-_Heart_of_the_Andes_-_Google_Art_Project.jpg",
    credit: "Heart of the Andes — Frederic Edwin Church, 1859",
    link: "https://commons.wikimedia.org/wiki/File:Frederic_Edwin_Church_-_Heart_of_the_Andes_-_Google_Art_Project.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Turner_-_Rain%2C_Steam_and_Speed_-_National_Gallery_file.jpg/1920px-Turner_-_Rain%2C_Steam_and_Speed_-_National_Gallery_file.jpg",
    credit: "Rain, Steam and Speed — J.M.W. Turner, 1844",
    link: "https://commons.wikimedia.org/wiki/File:Turner_-_Rain,_Steam_and_Speed_-_National_Gallery_file.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Caspar_David_Friedrich_-_Das_Eismeer_-_Hamburger_Kunsthalle_-_02.jpg/1920px-Caspar_David_Friedrich_-_Das_Eismeer_-_Hamburger_Kunsthalle_-_02.jpg",
    credit: "The Sea of Ice (Das Eismeer) — Caspar David Friedrich, 1824",
    link: "https://commons.wikimedia.org/wiki/File:Caspar_David_Friedrich_-_Das_Eismeer_-_Hamburger_Kunsthalle_-_02.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/John_Martin_-_The_Great_Day_of_His_Wrath_-_Google_Art_Project.jpg/1920px-John_Martin_-_The_Great_Day_of_His_Wrath_-_Google_Art_Project.jpg",
    credit: "The Great Day of His Wrath — John Martin, 1851–1853",
    link: "https://commons.wikimedia.org/wiki/File:John_Martin_-_The_Great_Day_of_His_Wrath_-_Google_Art_Project.jpg",
    source: "Wikimedia Commons · Public Domain",
  },
  {
    url: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=1920&q=90&auto=format&fit=max",
    credit: "Su San Lee",
    link: "https://unsplash.com/@s_s_lee",
    source: "Unsplash",
    title: "Cherry Blossoms",
    culture: "japanese",
  },
  {
    url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1920&q=90&auto=format&fit=max",
    credit: "Federico Respini",
    link: "https://unsplash.com/@federicorespini",
    source: "Unsplash",
    title: "Golden Fields",
  },
  {
    url: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1920&q=90&auto=format&fit=max",
    credit: "Sebastian Unrau",
    link: "https://unsplash.com/@sebastian_unrau",
    source: "Unsplash",
    title: "Winter Pines",
  },
  {
    url: "https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=1920&q=90&auto=format&fit=max",
    credit: "Leonard Cotte",
    link: "https://unsplash.com/@leonardcotte",
    source: "Unsplash",
    title: "City at Night",
  },
  {
    url: "https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=1920&q=90&auto=format&fit=max",
    credit: "Johny Goerend",
    link: "https://unsplash.com/@johnygoerend",
    source: "Unsplash",
    title: "Desert Dunes",
  },
  {
    url: "https://images.unsplash.com/photo-1477601263568-180e2c6d046e?w=1920&q=90&auto=format&fit=max",
    credit: "Joshua Earle",
    link: "https://unsplash.com/@joshuaearle",
    source: "Unsplash",
    title: "Mountain Hiker",
  },
  {
    url: "https://images.unsplash.com/photo-1464852045489-bccb7d17fe39?w=1920&q=90&auto=format&fit=max",
    credit: "Denis Degioanni",
    link: "https://unsplash.com/@denisdegioanni",
    source: "Unsplash",
    title: "Starry Night Sky",
  },
  {
    url: "https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=1920",
    credit: "Michael Block",
    link: "https://www.pexels.com/@michael-block-1691617",
    source: "Pexels",
    title: "Forest Road",
  },
  {
    url: "https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg?auto=compress&cs=tinysrgb&w=1920",
    credit: "James Wheeler",
    link: "https://www.pexels.com/@souvenirpixels",
    source: "Pexels",
    title: "Autumn Lake",
  },
  {
    url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?w=1920&q=90&auto=format&fit=max",
    credit: "Kazuend",
    link: "https://unsplash.com/@kazuend",
    source: "Unsplash",
    title: "Tall Redwoods",
    culture: "indigenous",
  },
  {
    url: "https://images.unsplash.com/photo-1476231682828-37e571bc172f?w=1920&q=90&auto=format&fit=max",
    credit: "Robert Lukeman",
    link: "https://unsplash.com/@robertlukeman",
    source: "Unsplash",
    title: "Forest Stream",
    culture: "indigenous",
  },
  {
    url: "https://images.unsplash.com/photo-1425913397330-cf8af2ff40a1?w=1920&q=90&auto=format&fit=max",
    credit: "Sebastian Unrau",
    link: "https://unsplash.com/@sebastian_unrau",
    source: "Unsplash",
    title: "Misty Pine Forest",
    culture: "indigenous",
  },
  {
    url: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=1920&q=90&auto=format&fit=max",
    credit: "Todd Quackenbush",
    link: "https://unsplash.com/@toddquackenbush",
    source: "Unsplash",
    title: "Sunlit Trees",
    culture: "indigenous",
  },
  {
    url: "https://images.unsplash.com/photo-1440581572325-0bea30075d9d?w=1920&q=90&auto=format&fit=max",
    credit: "Luca Bravo",
    link: "https://unsplash.com/@lucabravo",
    source: "Unsplash",
    title: "Birch Forest",
    culture: "indigenous",
  },
  {
    url: "https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=1920&q=90&auto=format&fit=max",
    credit: "Lukasz Szmigiel",
    link: "https://unsplash.com/@szmigieldesign",
    source: "Unsplash",
    title: "Forest Canopy",
    culture: "indigenous",
  },
  {
    url: "https://images.unsplash.com/photo-1505765050516-f72dcac9c60e?w=1920&q=90&auto=format&fit=max",
    credit: "Dave Hoefler",
    link: "https://unsplash.com/@davehoefler",
    source: "Unsplash",
    title: "Autumn Lake",
  },
  {
    url: "https://images.unsplash.com/photo-1518495973542-4542c06a5843?w=1920&q=90&auto=format&fit=max",
    credit: "Daan Weijers",
    link: "https://unsplash.com/@daanweijer",
    source: "Unsplash",
    title: "Sunbeams Through Trees",
  },
  {
    url: "https://images.unsplash.com/photo-1500534623283-312aade485b7?w=1920&q=90&auto=format&fit=max",
    credit: "Robert Bye",
    link: "https://unsplash.com/@robertbye",
    source: "Unsplash",
    title: "Peaceful Lake",
  },
  {
    url: "https://images.unsplash.com/photo-1500964757637-c85e8a162699?w=1920&q=90&auto=format&fit=max",
    credit: "Simon Berger",
    link: "https://unsplash.com/@8moments",
    source: "Unsplash",
    title: "Golden Hills",
  },
  {
    url: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1920&q=90&auto=format&fit=max",
    credit: "Chandler Cruttenden",
    link: "https://unsplash.com/@chancruttenden",
    source: "Unsplash",
    title: "Snowy Road",
  },
  {
    url: "https://images.unsplash.com/photo-1507400492013-162706c8c05e?w=1920&q=90&auto=format&fit=max",
    credit: "Kym MacKinnon",
    link: "https://unsplash.com/@vixenly",
    source: "Unsplash",
    title: "Pink Dawn",
  },
  {
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1920&q=90&auto=format&fit=max",
    credit: "Bailey Zindel",
    link: "https://unsplash.com/@baileyzindel",
    source: "Unsplash",
    title: "Valley Dawn",
  },
  {
    url: "https://images.unsplash.com/photo-1490730141103-6cac27aaab94?w=1920&q=90&auto=format&fit=max",
    credit: "Joshua Earle",
    link: "https://unsplash.com/@joshuaearle",
    source: "Unsplash",
    title: "Sunrise Silhouette",
  },
  {
    url: "https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?w=1920&q=90&auto=format&fit=max",
    credit: "Joshua Earle",
    link: "https://unsplash.com/@joshuaearle",
    source: "Unsplash",
    title: "Forest Sunset",
  },
  {
    url: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=1920&q=90&auto=format&fit=max",
    credit: "Casey Horner",
    link: "https://unsplash.com/@mischievous_penguins",
    source: "Unsplash",
    title: "Tree Canopy Light",
  },
  {
    url: "https://images.unsplash.com/photo-1483664852095-d6cc6870702d?w=1920&q=90&auto=format&fit=max",
    credit: "Khamkeo Vilaysing",
    link: "https://unsplash.com/@mahkeo",
    source: "Unsplash",
    title: "Frosty Forest",
  },
  {
    url: "https://images.unsplash.com/photo-1517299321609-52687d1bc55a?w=1920&q=90&auto=format&fit=max",
    credit: "Nathan Anderson",
    link: "https://unsplash.com/@nathananderson",
    source: "Unsplash",
    title: "Snow Peaks",
  },
  {
    url: "https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=1920&q=90&auto=format&fit=max",
    credit: "Frank McKenna",
    link: "https://unsplash.com/@frankiefoto",
    source: "Unsplash",
    title: "Ocean Aerial",
  },
  {
    url: "https://images.unsplash.com/photo-1468581264429-2548ef9eb732?w=1920&q=90&auto=format&fit=max",
    credit: "Jeremy Bishop",
    link: "https://unsplash.com/@jeremybishop",
    source: "Unsplash",
    title: "Sea Rocks",
  },
  {
    url: "https://images.unsplash.com/photo-1471922694854-ff1b63b20054?w=1920&q=90&auto=format&fit=max",
    credit: "Anastasia Taioglou",
    link: "https://unsplash.com/@tfrlee",
    source: "Unsplash",
    title: "Blue Coast",
  },
  {
    url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=1920&q=90&auto=format&fit=max",
    credit: "Matt Hardy",
    link: "https://unsplash.com/@matthardy",
    source: "Unsplash",
    title: "Ocean Waves",
  },
  {
    url: "https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=1920&q=90&auto=format&fit=max",
    credit: "Sven Scheuermeier",
    link: "https://unsplash.com/@sveninho",
    source: "Unsplash",
    title: "Alpine Summit",
  },
  {
    url: "https://images.unsplash.com/photo-1464278533981-50106e6176b1?w=1920&q=90&auto=format&fit=max",
    credit: "Joshua Earle",
    link: "https://unsplash.com/@joshuaearle",
    source: "Unsplash",
    title: "Lone Wanderer",
  },
  {
    url: "https://images.unsplash.com/photo-1491466424936-e304919aada7?w=1920&q=90&auto=format&fit=max",
    credit: "Dino Reichmuth",
    link: "https://unsplash.com/@dinoreichmuth",
    source: "Unsplash",
    title: "Mountain Road",
  },
  {
    url: "https://images.unsplash.com/photo-1445363692815-ebcd599f7621?w=1920&q=90&auto=format&fit=max",
    credit: "Ales Krivec",
    link: "https://unsplash.com/@aleskrivec",
    source: "Unsplash",
    title: "Mountain Chapel",
  },
  {
    url: "https://images.unsplash.com/photo-1434394354979-a235cd36269d?w=1920&q=90&auto=format&fit=max",
    credit: "Pedro Lastra",
    link: "https://unsplash.com/@peterlaster",
    source: "Unsplash",
    title: "Canyon Sunset",
  },
  {
    url: "https://images.unsplash.com/photo-1458668383970-8ddd3927deed?w=1920&q=90&auto=format&fit=max",
    credit: "Sven Fischer",
    link: "https://unsplash.com/@svenfischer",
    source: "Unsplash",
    title: "Swiss Alps",
  },
  {
    url: "https://images.unsplash.com/photo-1510797215324-95aa89f43c33?w=1920&q=90&auto=format&fit=max",
    credit: "Timothy Eberly",
    link: "https://unsplash.com/@timothyeberly",
    source: "Unsplash",
    title: "Golden Grass",
  },
  {
    url: "https://images.unsplash.com/photo-1504567961542-e24d9439a724?w=1920&q=90&auto=format&fit=max",
    credit: "Geran de Klerk",
    link: "https://unsplash.com/@gerandeklerk",
    source: "Unsplash",
    title: "Lavender Rows",
  },
  {
    url: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1920&q=90&auto=format&fit=max",
    credit: "Braden Jarvis",
    link: "https://unsplash.com/@bradenjarvis",
    source: "Unsplash",
    title: "Desert Highway",
  },
  {
    url: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=1920&q=90&auto=format&fit=max",
    credit: "Cosmic Timetraveler",
    link: "https://unsplash.com/@cosmictimetraveler",
    source: "Unsplash",
    title: "Desert Dunes",
  },
  {
    url: "https://images.unsplash.com/photo-1473580044384-7ba9967e16a0?w=1920&q=90&auto=format&fit=max",
    credit: "Willian Justen de Vasconcellos",
    link: "https://unsplash.com/@willianjusten",
    source: "Unsplash",
    title: "Red Rock Canyon",
  },
  {
    url: "https://images.unsplash.com/photo-1495567720989-cebdbdd97913?w=1920&q=90&auto=format&fit=max",
    credit: "Fabian Quintero",
    link: "https://unsplash.com/@fabianquintero",
    source: "Unsplash",
    title: "Lone Tree Sunset",
  },
  {
    url: "https://images.unsplash.com/photo-1444703686981-a3abbc4d4fe3?w=1920&q=90&auto=format&fit=max",
    credit: "Greg Rakozy",
    link: "https://unsplash.com/@grakozy",
    source: "Unsplash",
    title: "Night Sky",
  },
  {
    url: "https://images.unsplash.com/photo-1465101162946-4377e57745c3?w=1920&q=90&auto=format&fit=max",
    credit: "Jeremy Thomas",
    link: "https://unsplash.com/@jeremythomasphoto",
    source: "Unsplash",
    title: "Galaxy View",
  },
  {
    url: "https://images.unsplash.com/photo-1431794062232-2a99a5431c6c?w=1920&q=90&auto=format&fit=max",
    credit: "Ales Krivec",
    link: "https://unsplash.com/@aleskrivec",
    source: "Unsplash",
    title: "Village Valley",
  },
  {
    url: "https://images.unsplash.com/photo-1510784722466-f2aa9c52fff6?w=1920&q=90&auto=format&fit=max",
    credit: "Eberhard Grossgasteiger",
    link: "https://unsplash.com/@eberhardgross",
    source: "Unsplash",
    title: "Turquoise Lake",
  },
  {
    url: "https://images.unsplash.com/photo-1439853949127-fa647821eba0?w=1920&q=90&auto=format&fit=max",
    credit: "Ales Krivec",
    link: "https://unsplash.com/@aleskrivec",
    source: "Unsplash",
    title: "Emerald Valley",
  },
  {
    url: "https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=1920&q=90&auto=format&fit=max",
    credit: "Ricardo Gomez Angel",
    link: "https://unsplash.com/@rgaleriacom",
    source: "Unsplash",
    title: "Autumn Leaves",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Vincent_van_Gogh_-_Wheatfield_with_crows_-_Google_Art_Project.jpg/1920px-Vincent_van_Gogh_-_Wheatfield_with_crows_-_Google_Art_Project.jpg",
    credit: "Vincent van Gogh",
    link: "https://en.wikipedia.org/wiki/Wheatfield_with_Crows",
    source: "Wikimedia Commons",
    title: "Wheatfield with Crows",
  },
  {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg/1920px-A_Sunday_on_La_Grande_Jatte%2C_Georges_Seurat%2C_1884.jpg",
    credit: "Georges Seurat",
    link: "https://en.wikipedia.org/wiki/A_Sunday_Afternoon_on_the_Island_of_La_Grande_Jatte",
    source: "Wikimedia Commons",
    title: "Sunday on La Grande Jatte",
  },
  {
    url: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1920&q=90&auto=format&fit=max",
    credit: "Qingbao Meng",
    link: "https://unsplash.com/@qbqn",
    source: "Unsplash",
    title: "Terraced Mountains",
  },
  {
    url: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=1920&q=90&auto=format&fit=max",
    credit: "Luca Bravo",
    link: "https://unsplash.com/@lucabravo",
    source: "Unsplash",
    title: "Mountain Lake Cabin",
  },
  {
    url: "https://images.unsplash.com/photo-1447752875215-b2761acb3c5d?w=1920&q=90&auto=format&fit=max",
    credit: "Tim Mossholder",
    link: "https://unsplash.com/@timmossholder",
    source: "Unsplash",
    title: "Forest Canopy Path",
  },
  {
    url: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=1920&q=90&auto=format&fit=max",
    credit: "Greg Rakozy",
    link: "https://unsplash.com/@grakozy",
    source: "Unsplash",
    title: "Milky Way Arch",
  },
  {
    url: "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=1920&q=90&auto=format&fit=max",
    credit: "Luca Bravo",
    link: "https://unsplash.com/@lucabravo",
    source: "Unsplash",
    title: "Dolomite Peaks",
  },
  {
    url: "https://images.unsplash.com/photo-1540202404-a2f29016b523?w=1920&q=90&auto=format&fit=max",
    credit: "Silas Baisch",
    link: "https://unsplash.com/@silasbaisch",
    source: "Unsplash",
    title: "Turquoise Coast",
  },
  {
    url: "https://images.unsplash.com/photo-1497436072909-60f360e1d4b1?w=1920&q=90&auto=format&fit=max",
    credit: "Marivi Pazos",
    link: "https://unsplash.com/@marivipazos",
    source: "Unsplash",
    title: "Nordic Fjords",
  },
  {
    url: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=1920&q=90&auto=format&fit=max",
    credit: "Cristina Gottardi",
    link: "https://unsplash.com/@cristina_gottardi",
    source: "Unsplash",
    title: "Snow Ridge",
  },
  {
    url: "https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?w=1920&q=90&auto=format&fit=max",
    credit: "Quino Al",
    link: "https://unsplash.com/@quinoal",
    source: "Unsplash",
    title: "Golden Sunrise Field",
  }
];
